# Generated by Django 5.1.1 on 2024-09-30 08:14
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        CITextExtension() # makes the the field case insensitive
    ]
